### ISSUE TITLE
How can I utilize this package with the built-in webcam on Ubuntu 20.04, galactic laptop?

### ISSUE THREAD

**Issue by mabasith** [ros-drivers/usb_cam#256] opened 2023-06-09 10:02 UTC
i got this error with laptop web cam: undefined symbol: _ZN12class_loader4impl22AbstractMetaObjectBaseC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_

**Comment by twdragon** [comment] 2023-06-09 11:06
It does not seem the problem is with the node, and it is impossible to see which library is actually involved. Please share a bit more information about your setup and run

**Comment by mabasith** [comment] 2023-06-09 11:26
Ubundu 20.04,
ROS2 Galactic.
branch: ros2 of this repo.
launch file: ros2 launch usb_cam demo_launch.py.
error: symbol lookup error: + undefined symbol: _ZN12class_loader4impl22AbstractMetaObjectBaseC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_

**Comment by twdragon** [comment] 2023-06-09 14:19
I guess it is a problem with your ROS installation, some libraries are missing. The node does not utilize MetaObjects directly

**Comment by flynneva** [comment] 2023-06-11 03:00
@mabasith doing a quick google search it looks like this has to do with your local ROS installation and ensuring you do not cross different ROS workspaces / distros.

https://answers.ros.org/question/354332/rosbag2_bag_v2_plugins-install-issue/

I'll go ahead and close this issue since this is not related to this package 👍🏼

**Closed by flynneva** 2023-06-11 03:00 UTC
