### ISSUE TITLE
[ WARN] [1451228881.432495085]: sh: 1: v4l2-ctl: not found

### ISSUE THREAD

**Issue by bloong** [ros-drivers/usb_cam#43] opened 2015-12-27 15:20 UTC
I use this demo and run this cmd  $ roslaunch usb_cam usb_cam-test.launch  and it is warn the information as the title  "sh: 1: v4l2-ctl:not found", and my system is Ubuntu 14.04 with jade . the video can't display . I'm sure the camera is running normal becasue I use the geese I can see the video normal, I don't know how to solve it and who can help me ?

**Comment by bloong** [comment] 2015-12-27 15:53
I have solve this problem , change the  <param name="pixel_format" value="yuyv" /> to <param name="pixel_format" value="mjpeg" />

**Comment by YuxiHuang001** [comment] 2016-01-05 16:16
Because you do not install v4l-utils,you can try:sudo apt-get install v4l-utils

**Comment by pudumula** [comment] 2016-12-21 16:49
Hi @bloong pls close this issue if the problem is solved.

**Closed** 2017-08-17 06:12 UTC

**Comment by loulansuiye** [comment] 2018-07-05 07:41
[ERROR] [1530776452.480746348]: select timeout

**Comment by loulansuiye** [comment] 2018-07-05 07:41
mera_info/head_camera.yaml
[ INFO] [1530776447.357973264]: Starting 'head_camera' (/dev/video0) at 800x600 via mmap (yuyv) at 30 FPS
[ WARN] [1530776447.475193111]: unknown control 'focus_auto'

[ERROR] [1530776452.480746348]: select timeout

**Comment by rjosodtssp** [comment] 2019-03-19 07:12
> I have solve this problem , change the to
change what ? speak out
